"""Streamlit dashboard for `lia oi-dashboard` — live rolling view of the
current week's expirations.

Renders one column per expiration date across the next N business days
(default 5, starting today or the next business day if it's a weekend).
Auto-refreshes every 30s so any PNG regenerated by `oi_batch.py` — either
manually via the "Run batch now" button, or by a background cron — shows
up here without a page reload.

Run locally:

    UV_NATIVE_TLS=true uv run streamlit run scripts/oi_dashboard_app.py

Open in your browser at the URL Streamlit prints (usually
http://localhost:8501).
"""
from __future__ import annotations

import os
import subprocess
import sys
import time
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import numpy as np
import plotly.graph_objects as go
import streamlit as st
from streamlit_autorefresh import st_autorefresh

REPO_ROOT = Path(__file__).resolve().parent.parent
PLOTS_DIR = REPO_ROOT / "plots"
BATCH_SCRIPT = REPO_ROOT / "scripts" / "oi_batch.py"

# Reuse the private helpers from `julia.main` so the crossing math
# matches exactly what the PNG dashboard shows.
sys.path.insert(0, str(REPO_ROOT / "src"))
from julia import gex_store  # noqa: E402
from julia.main import (  # noqa: E402
    _find_curve_crossing,
    _load_oi_snapshot_df,
    _prepare_oi_series,
)


# ---------------------------------------------------------------------------
# Date helpers
# ---------------------------------------------------------------------------

def _next_business_day(d: date) -> date:
    while d.weekday() >= 5:
        d += timedelta(days=1)
    return d


def _add_business_days(d: date, n: int) -> date:
    """Return the date `n` business days after `d` (n=0 → d itself)."""
    while n > 0:
        d += timedelta(days=1)
        if d.weekday() < 5:
            n -= 1
    return d


def _compute_range(days_ahead: int) -> tuple[date, date, list[date]]:
    start = _next_business_day(date.today())
    end = _add_business_days(start, days_ahead - 1)
    exps: list[date] = []
    d = start
    while d <= end:
        if d.weekday() < 5:
            exps.append(d)
        d += timedelta(days=1)
    return start, end, exps


# ---------------------------------------------------------------------------
# PNG helpers
# ---------------------------------------------------------------------------

def _png_for(ticker: str, exp: date) -> Path:
    return PLOTS_DIR / f"oi-dashboard-{ticker}-{exp.isoformat()}.png"


def _age_str(path: Path) -> str:
    if not path.exists():
        return "not generated"
    mtime = datetime.fromtimestamp(path.stat().st_mtime)
    delta = datetime.now() - mtime
    secs = int(delta.total_seconds())
    if secs < 60:
        return f"{secs}s ago"
    if secs < 3600:
        return f"{secs // 60}m ago"
    if secs < 86400:
        return f"{secs // 3600}h {(secs % 3600) // 60}m ago"
    return f"{secs // 86400}d ago"


# ---------------------------------------------------------------------------
# Crossing-strike time series
# ---------------------------------------------------------------------------

def _parse_utc(iso_ts: str) -> datetime:
    return datetime.fromisoformat(iso_ts.replace("Z", "+00:00"))


def _crossing_history(ticker: str, expiration: date) -> list[dict]:
    """For each snapshot of (ticker, expiration), compute the cumulative
    dollar-OI crossing strike and pair it with the spot at that moment.

    Returns a list of dicts sorted oldest → newest so plotting is a
    straight time series. Skips snapshots that don't have enough data to
    compute a crossing (e.g. one-sided chains).
    """
    rows = gex_store.recent_snapshots(
        ticker=ticker, expiration_date=expiration.isoformat(), limit=500
    )
    if not rows:
        return []

    history: list[dict] = []
    for r in rows:
        df = _load_oi_snapshot_df(r)
        if df is None or df.empty:
            continue
        spot = float(r["spot_price"])
        series = _prepare_oi_series(df, spot=spot, metric="dollars", range_pct=0)
        if series is None:
            continue
        call_cum = np.cumsum(series["call_vals"])
        put_arr = np.array(series["put_vals_positive"])
        put_cum = np.cumsum(put_arr[::-1])[::-1]
        cx, cy = _find_curve_crossing(series["strikes"], call_cum, put_cum)
        if cx is None:
            continue
        history.append({
            "captured_at_utc": _parse_utc(r["captured_at"]),
            "captured_at_local": _parse_utc(r["captured_at"]).astimezone(),
            "crossing_strike": float(cx),
            "crossing_dollars": float(cy) if cy is not None else None,
            "spot_price": spot,
        })

    history.sort(key=lambda h: h["captured_at_utc"])
    return history


def _render_crossing_chart(ticker: str, expiration: date, history: list[dict]) -> None:
    if not history:
        st.info(
            f"No snapshots yet for {ticker} {expiration.isoformat()}. "
            "Run **oi-dashboard** at least once to seed the history."
        )
        return

    ts = [h["captured_at_local"] for h in history]
    cross = [h["crossing_strike"] for h in history]
    spot = [h["spot_price"] for h in history]
    single = len(history) == 1

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=ts, y=cross,
        mode="markers" if single else "lines+markers",
        name="Crossing strike",
        line=dict(color="#1f77b4", width=2.5),
        marker=dict(size=12 if single else 8, color="#1f77b4"),
        hovertemplate=(
            "<b>%{x|%Y-%m-%d %H:%M}</b><br>"
            "Crossing: <b>$%{y:.2f}</b><extra></extra>"
        ),
    ))
    fig.add_trace(go.Scatter(
        x=ts, y=spot,
        mode="markers" if single else "lines+markers",
        name="Spot",
        line=dict(color="#111", dash="dash", width=1.5),
        marker=dict(size=10 if single else 6, symbol="circle-open", color="#111"),
        hovertemplate=(
            "<b>%{x|%Y-%m-%d %H:%M}</b><br>"
            "Spot: <b>$%{y:.2f}</b><extra></extra>"
        ),
    ))

    first, last = history[0], history[-1]
    delta_cross = last["crossing_strike"] - first["crossing_strike"]
    delta_spot = last["spot_price"] - first["spot_price"]
    span_min = (last["captured_at_utc"] - first["captured_at_utc"]).total_seconds() / 60
    if single:
        span_str = "single snapshot"
    else:
        span_str = (
            f"{span_min / 60 / 24:.1f} days" if span_min >= 60 * 24
            else f"{span_min / 60:.1f} hours" if span_min >= 60
            else f"{span_min:.0f} min"
        )

    # With a single point, Plotly's autorange picks a tiny window and the
    # dot floats in the middle of nowhere. Pad the y-axis so the dot + spot
    # sit at a sensible scale, and widen the x-axis so it doesn't look like
    # the chart is broken.
    layout_kwargs: dict = dict(
        title=(
            f"{ticker} {expiration.isoformat()} — crossing strike over time  "
            f"·  {len(history)} snapshot{'s' if len(history) != 1 else ''} "
            f"over {span_str}"
        ),
        xaxis_title="Snapshot time (local)",
        yaxis_title="Strike ($)",
        height=380,
        hovermode="x unified",
        legend=dict(orientation="h", y=1.08, x=0),
        margin=dict(t=60, l=60, r=20, b=40),
    )
    if single:
        t0 = ts[0]
        layout_kwargs["xaxis"] = dict(
            range=[t0 - timedelta(hours=6), t0 + timedelta(hours=6)],
        )
        lo = min(cross[0], spot[0])
        hi = max(cross[0], spot[0])
        pad = max((hi - lo) * 2.0, 2.0)
        layout_kwargs["yaxis"] = dict(range=[lo - pad, hi + pad])

    fig.update_layout(**layout_kwargs)
    fig.update_yaxes(tickformat="$.2f")

    st.plotly_chart(fig, use_container_width=True)

    col_a, col_b, col_c = st.columns(3)
    with col_a:
        st.metric(
            "Latest crossing",
            f"${last['crossing_strike']:.2f}",
            None if single else f"{delta_cross:+.2f} vs first",
        )
    with col_b:
        st.metric(
            "Latest spot",
            f"${last['spot_price']:.2f}",
            None if single else f"{delta_spot:+.2f} vs first",
        )
    with col_c:
        gap = last["crossing_strike"] - last["spot_price"]
        st.metric(
            "Crossing − spot (now)",
            f"{gap:+.2f}",
            help=(
                "Positive = the pin/max-pain magnet is above spot; "
                "negative = below."
            ),
        )
    if single:
        st.caption(
            "Only one snapshot so far — run `oi-dashboard` again "
            "(or the batch) to start seeing movement over time."
        )


# ---------------------------------------------------------------------------
# Background batch runner
# ---------------------------------------------------------------------------

def _kickoff_batch(
    tickers: list[str],
    start: date,
    end: date,
    refresh_cache: bool,
) -> None:
    """Spawn oi_batch.py as a background subprocess (non-blocking)."""
    cmd = [
        str(BATCH_SCRIPT),
        "--from", start.isoformat(),
        "--to", end.isoformat(),
        "--tickers", ",".join(tickers),
    ]
    if not refresh_cache:
        cmd.append("--no-refresh-cache")

    env = os.environ.copy()
    env.setdefault("UV_NATIVE_TLS", "true")

    log_path = REPO_ROOT / "logs" / "oi-batch" / "_streamlit_last_run.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_file = open(log_path, "w")

    proc = subprocess.Popen(
        cmd, cwd=REPO_ROOT, env=env, stdout=log_file, stderr=subprocess.STDOUT,
    )
    st.session_state["_batch_proc"] = proc
    st.session_state["_batch_log_path"] = str(log_path)
    st.session_state["_batch_started_at"] = time.time()


def _poll_batch() -> str:
    """Return one of: 'idle', 'running', 'done', 'failed'."""
    proc = st.session_state.get("_batch_proc")
    if proc is None:
        return "idle"
    rc = proc.poll()
    if rc is None:
        return "running"
    st.session_state["_batch_rc"] = rc
    st.session_state["_batch_finished_at"] = time.time()
    st.session_state["_batch_proc"] = None
    return "done" if rc == 0 else "failed"


# ---------------------------------------------------------------------------
# Main app
# ---------------------------------------------------------------------------

st.set_page_config(page_title="Options OI Dashboard", layout="wide")
st.title("📊 Options OI — Live Dashboard")

with st.sidebar:
    st.header("Config")
    tickers_str = st.text_input(
        "Tickers (comma-separated)",
        value=st.session_state.get("tickers_str", "SPY"),
        key="tickers_str",
    )
    tickers = [
        t.strip().upper() for t in tickers_str.split(",") if t.strip()
    ]
    days_ahead = st.slider(
        "Business days ahead (starting today)",
        min_value=1, max_value=10, value=5, key="days_ahead",
    )
    refresh_cache = st.toggle(
        "Force fresh Robinhood fetch (slow, ~60–90s per date)",
        value=False, key="refresh_cache",
        help=(
            "Off = use cached options chain (fast; premium may be a few "
            "minutes stale). On = pass --refresh-cache to oi_batch so "
            "every job pulls a live chain."
        ),
    )

    st.divider()
    st.subheader("Refresh")
    auto = st.toggle("Auto-refresh every 30s", value=True, key="auto")
    if auto:
        st_autorefresh(interval=30_000, key="_autoref")

    col_r1, col_r2 = st.columns(2)
    with col_r1:
        if st.button("🔄 Refresh view", use_container_width=True):
            st.rerun()
    with col_r2:
        batch_state = _poll_batch()
        run_disabled = batch_state == "running"
        if st.button(
            "▶ Run batch",
            type="primary",
            use_container_width=True,
            disabled=run_disabled,
        ):
            start, end, _ = _compute_range(days_ahead)
            _kickoff_batch(tickers, start, end, refresh_cache)
            st.rerun()


start, end, exps = _compute_range(days_ahead)

top1, top2, top3 = st.columns([2, 2, 3])
with top1:
    st.metric("Range start", start.isoformat())
with top2:
    st.metric("Range end", end.isoformat())
with top3:
    st.metric("Expirations", f"{len(exps)}  ·  {', '.join(t for t in tickers)}")

batch_state = _poll_batch()
if batch_state == "running":
    elapsed = int(time.time() - st.session_state.get("_batch_started_at", time.time()))
    st.warning(
        f"🚀 Batch running… ({elapsed}s elapsed). "
        f"PNGs will appear here as each date finishes; auto-refresh keeps "
        f"the view current."
    )
    log_path = st.session_state.get("_batch_log_path")
    if log_path and Path(log_path).exists():
        with st.expander("Live batch log"):
            st.code(Path(log_path).read_text()[-4000:], language="text")
elif batch_state == "done":
    finished = st.session_state.get("_batch_finished_at")
    if finished:
        st.success(f"✅ Batch completed at {datetime.fromtimestamp(finished).strftime('%H:%M:%S')}")
elif batch_state == "failed":
    rc = st.session_state.get("_batch_rc")
    st.error(f"❌ Batch failed (rc={rc}). See log:")
    log_path = st.session_state.get("_batch_log_path")
    if log_path and Path(log_path).exists():
        st.code(Path(log_path).read_text()[-4000:], language="text")

st.caption(
    f"Dashboard view refreshed at "
    f"**{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}** "
    f"(local). Charts + PNGs are re-read from the DB / disk on every refresh."
)

# ---------------------------------------------------------------------------
# Crossing-strike time series (interactive, one per ticker × expiration)
# ---------------------------------------------------------------------------
st.divider()
st.header("📈 Crossing strike over time")
st.caption(
    "Where the cumulative-dollar call and put curves cross — the "
    "positioning-weighted 'pin' strike. Each `oi-dashboard` run adds a "
    "point. Watch for drift: crossing moving toward or away from spot."
)

for ticker in tickers:
    if not exps:
        continue
    tabs = st.tabs([f"{exp.isoformat()} ({exp.strftime('%a')})" for exp in exps])
    for tab, exp in zip(tabs, exps):
        with tab:
            st.markdown(f"**{ticker} · {exp.isoformat()}**")
            history = _crossing_history(ticker, exp)
            _render_crossing_chart(ticker, exp, history)

# ---------------------------------------------------------------------------
# PNG grid (the three-panel dashboard as static images for now)
# ---------------------------------------------------------------------------
st.divider()
st.header("🖼 Latest dashboard PNGs")
st.caption(
    "The full 3-panel `oi-dashboard` snapshots as generated by `oi_batch.py`. "
    "Interactive Plotly versions of these panels are a natural next step."
)

for ticker in tickers:
    st.subheader(f"{ticker}")
    if not exps:
        st.info("No business days in the selected range.")
        continue
    cols = st.columns(len(exps))
    for col, exp in zip(cols, exps):
        with col:
            path = _png_for(ticker, exp)
            age = _age_str(path)
            weekday = exp.strftime("%a")
            st.markdown(f"**{exp.isoformat()}** ({weekday})  ·  _{age}_")
            if path.exists():
                st.image(str(path), use_container_width=True)
            else:
                st.info(
                    "No PNG yet.\n\n"
                    "Click **▶ Run batch** in the sidebar to generate it."
                )
