"""Streamlit dashboard for `lia oi-dashboard` — live rolling view of the
current week's expirations.

Renders one column per expiration date across the next N business days
(default 5, starting today or the next business day if it's a weekend).
Auto-refreshes every 30s so any PNG regenerated by `oi_batch.py` — either
manually via the "Run batch now" button, or by a background cron — shows
up here without a page reload.

Run locally:

    UV_NATIVE_TLS=true uv run streamlit run scripts/oi_dashboard_app.py

Open in your browser at the URL Streamlit prints (usually
http://localhost:8501).
"""
from __future__ import annotations

import os
import subprocess
import sys
import time
from datetime import date, datetime, timedelta
from pathlib import Path

import math

import numpy as np
import plotly.graph_objects as go
import streamlit as st
from scipy.stats import norm
from streamlit_autorefresh import st_autorefresh

REPO_ROOT = Path(__file__).resolve().parent.parent
PLOTS_DIR = REPO_ROOT / "plots"
BATCH_SCRIPT = REPO_ROOT / "scripts" / "oi_batch.py"

# Reuse the private helpers from `julia.main` so the crossing math
# matches exactly what the PNG dashboard shows.
sys.path.insert(0, str(REPO_ROOT / "src"))
from julia import gex_store  # noqa: E402
from julia.main import (  # noqa: E402
    _find_curve_crossing,
    _load_oi_snapshot_df,
    _prepare_oi_series,
)


# ---------------------------------------------------------------------------
# Date helpers
# ---------------------------------------------------------------------------

def _next_business_day(d: date) -> date:
    while d.weekday() >= 5:
        d += timedelta(days=1)
    return d


def _add_business_days(d: date, n: int) -> date:
    """Return the date `n` business days after `d` (n=0 → d itself)."""
    while n > 0:
        d += timedelta(days=1)
        if d.weekday() < 5:
            n -= 1
    return d


def _prev_business_day(d: date) -> date:
    """The last business day strictly before ``d``."""
    d -= timedelta(days=1)
    while d.weekday() >= 5:
        d -= timedelta(days=1)
    return d


def _past_business_days(end: date, n: int) -> list[date]:
    """The ``n`` business days ending at ``end`` (inclusive), oldest first."""
    days: list[date] = []
    d = end
    while len(days) < n:
        if d.weekday() < 5:
            days.append(d)
        d -= timedelta(days=1)
    days.reverse()
    return days


def _compute_range(days_ahead: int) -> tuple[date, date, list[date]]:
    start = _next_business_day(date.today())
    end = _add_business_days(start, days_ahead - 1)
    exps: list[date] = []
    d = start
    while d <= end:
        if d.weekday() < 5:
            exps.append(d)
        d += timedelta(days=1)
    return start, end, exps


# ---------------------------------------------------------------------------
# PNG helpers
# ---------------------------------------------------------------------------

def _png_for(ticker: str, exp: date) -> Path:
    return PLOTS_DIR / f"oi-dashboard-{ticker}-{exp.isoformat()}.png"


def _format_age(secs: int) -> str:
    """Turn an integer number of seconds into a compact 'N ago' string."""
    if secs < 0:
        return "in the future?"
    if secs < 60:
        return f"{secs}s ago"
    if secs < 3600:
        return f"{secs // 60}m ago"
    if secs < 86400:
        return f"{secs // 3600}h {(secs % 3600) // 60}m ago"
    return f"{secs // 86400}d ago"


def _age_str(path: Path) -> str:
    if not path.exists():
        return "not generated"
    mtime = datetime.fromtimestamp(path.stat().st_mtime)
    return _format_age(int((datetime.now() - mtime).total_seconds()))


def _age_from_dt(dt: datetime) -> str:
    """Age of a timezone-aware datetime relative to 'now'."""
    now = datetime.now(dt.tzinfo) if dt.tzinfo else datetime.now()
    return _format_age(int((now - dt).total_seconds()))


# ---------------------------------------------------------------------------
# Crossing-strike time series
# ---------------------------------------------------------------------------

def _parse_utc(iso_ts: str) -> datetime:
    return datetime.fromisoformat(iso_ts.replace("Z", "+00:00"))


# ---------------------------------------------------------------------------
# Implied-move time series (68% / 95% / 99.7%)
# ---------------------------------------------------------------------------

# Same three levels the `emove` CLI prints. Tuple: (confidence, label, color).
IMPLIED_MOVE_LEVELS: list[tuple[float, str, str]] = [
    (0.6827, "68% (1σ)", "#1f77b4"),
    (0.9545, "95% (2σ)", "#ff7f0e"),
    (0.9973, "99.7% (3σ)", "#d62728"),
]
Z_BY_CONF: dict[float, float] = {
    conf: float(norm.ppf((1 + conf) / 2)) for conf, _, _ in IMPLIED_MOVE_LEVELS
}


def _business_days_between(start: date, end: date) -> int:
    """Trading-day count between ``start`` (exclusive) and ``end`` (inclusive).

    Matches the convention `emove` uses in ``sqrt(days / 252)``. Returns
    0 if ``end`` <= ``start`` (same-day or already-expired snapshot).
    """
    if end <= start:
        return 0
    d, count = start, 0
    while d < end:
        d += timedelta(days=1)
        if d.weekday() < 5:  # Mon=0..Fri=4
            count += 1
    return count


def _atm_iv_from_strikes(strikes, spot: float) -> float | None:
    """Average of call & put IV at the strike closest to spot.

    Returns ``None`` if we can't find a usable IV (illiquid chain,
    missing data). We snap to the nearest strike rather than
    interpolating because the strike grid is dense enough (usually $1
    for SPY) that interpolation adds noise, not accuracy.
    """
    if not strikes:
        return None
    # Find strike closest to spot
    nearest = min(strikes, key=lambda r: abs(float(r["strike_price"]) - spot))
    target_strike = float(nearest["strike_price"])

    ivs: list[float] = []
    for r in strikes:
        if abs(float(r["strike_price"]) - target_strike) > 1e-9:
            continue
        iv = r["implied_vol"]
        if iv is not None and iv > 0:
            ivs.append(float(iv))
    if not ivs:
        return None
    return sum(ivs) / len(ivs)


@st.cache_data(ttl=60, show_spinner=False)
def _implied_move_history(ticker: str, expiration_iso: str) -> list[dict]:
    """For each snapshot of (ticker, expiration), compute implied moves
    at 68%, 95%, and 99.7% confidence.

    Cached (60s TTL) because this hits ``get_strikes`` once per snapshot
    — non-trivial cost when the DB has hundreds of rows.

    Returned dicts include both $ and % moves per confidence level,
    plus the ATM IV that drove them (useful for the metric card).
    Sorted oldest → newest.
    """
    exp = date.fromisoformat(expiration_iso)
    rows = gex_store.recent_snapshots(
        ticker=ticker, expiration_date=expiration_iso, limit=500
    )
    if not rows:
        return []

    history: list[dict] = []
    for r in rows:
        spot = float(r["spot_price"])
        local_dt = _parse_utc(r["captured_at"]).astimezone()
        days = _business_days_between(local_dt.date(), exp)
        if days <= 0:
            continue  # expired / same-day
        strikes = gex_store.get_strikes(r["id"])
        iv = _atm_iv_from_strikes(strikes, spot)
        if iv is None:
            continue

        entry = {
            "captured_at_utc": _parse_utc(r["captured_at"]),
            "captured_at_local": local_dt,
            "spot": spot,
            "iv": iv,
            "days": days,
        }
        for conf, _, _ in IMPLIED_MOVE_LEVELS:
            move_dollars = spot * iv * math.sqrt(days / 252.0) * Z_BY_CONF[conf]
            entry[f"move_dollars_{conf}"] = move_dollars
            entry[f"move_pct_{conf}"] = (move_dollars / spot) * 100.0
        history.append(entry)

    history.sort(key=lambda h: h["captured_at_utc"])
    return history


def _render_implied_move_chart(
    ticker: str, expiration: date, history: list[dict], unit: str,
) -> None:
    """Render implied-move time series with 3 confidence bands.

    ``unit`` is either ``"pct"`` (Y-axis in % of spot) or ``"dollars"``
    (Y-axis in $). % is more comparable across expirations; $ is more
    concrete when comparing to spot moves.
    """
    if not history:
        st.info(
            f"No snapshots yet for {ticker} {expiration.isoformat()}. "
            "Run **oi-dashboard** at least once to seed the history."
        )
        return

    ts = [h["captured_at_local"] for h in history]
    single = len(history) == 1
    key = "move_pct" if unit == "pct" else "move_dollars"

    fig = go.Figure()
    for i, (conf, label, color) in enumerate(IMPLIED_MOVE_LEVELS):
        vals = [h[f"{key}_{conf}"] for h in history]
        # customdata rows: [spot, low_bound, high_bound, iv_pct,
        #                   move_pct, move_dollars, days]
        customdata = [
            [
                h["spot"],
                h["spot"] - h[f"move_dollars_{conf}"],
                h["spot"] + h[f"move_dollars_{conf}"],
                h["iv"] * 100,
                h[f"move_pct_{conf}"],
                h[f"move_dollars_{conf}"],
                h["days"],
            ]
            for h in history
        ]
        # Only the first trace shows the shared context (spot, IV, days
        # to expiry). Subsequent traces show only their specific move
        # info, so `hovermode="x unified"` doesn't repeat spot 3 times.
        if i == 0:
            hover = (
                "Spot at snapshot: <b>$%{customdata[0]:.2f}</b>  "
                "·  ATM IV <b>%{customdata[3]:.1f}%</b>  "
                "·  <b>%{customdata[6]}d</b> to exp<br>"
                f"±{label}: <b>±%{{customdata[4]:.2f}}%</b>  "
                "(±$%{customdata[5]:.2f})  →  "
                "<b>$%{customdata[1]:.2f} / $%{customdata[2]:.2f}</b>"
                "<extra></extra>"
            )
        else:
            hover = (
                f"±{label}: <b>±%{{customdata[4]:.2f}}%</b>  "
                "(±$%{customdata[5]:.2f})  →  "
                "<b>$%{customdata[1]:.2f} / $%{customdata[2]:.2f}</b>"
                "<extra></extra>"
            )
        fig.add_trace(go.Scatter(
            x=ts, y=vals,
            mode="markers" if single else "lines+markers",
            name=f"±{label}",
            line=dict(color=color, width=2.5),
            marker=dict(size=12 if single else 7, color=color),
            customdata=customdata,
            hovertemplate=hover,
        ))

    last = history[-1]
    days_note = f"{last['days']} trading day{'s' if last['days'] != 1 else ''} to expiry"
    fig.update_layout(
        title=(
            f"{ticker} {expiration.isoformat()} — implied move  "
            f"·  {len(history)} snapshot{'s' if len(history) != 1 else ''}  "
            f"·  {days_note} (at latest snapshot)"
        ),
        xaxis_title="Snapshot time (local)",
        yaxis_title=("Implied move (% of spot)" if unit == "pct" else "Implied move ($)"),
        height=380,
        hovermode="x unified",
        legend=dict(orientation="h", y=1.08, x=0),
        margin=dict(t=60, l=60, r=20, b=40),
    )
    if unit == "pct":
        fig.update_yaxes(ticksuffix="%")
    else:
        fig.update_yaxes(tickprefix="$")
    if single:
        t0 = ts[0]
        fig.update_xaxes(range=[t0 - timedelta(hours=6), t0 + timedelta(hours=6)])

    st.plotly_chart(fig, use_container_width=True)

    first = history[0]
    d_iv = last["iv"] - first["iv"]
    col_a, col_b, col_c, col_d = st.columns(4)
    for col, (conf, label, _color) in zip((col_a, col_b, col_c), IMPLIED_MOVE_LEVELS):
        with col:
            latest_val = last[f"{key}_{conf}"]
            latest_dollars = last[f"move_dollars_{conf}"]
            latest_pct = last[f"move_pct_{conf}"]
            if unit == "pct":
                headline = f"±{latest_val:.2f}%"
                sub = f"±${latest_dollars:.2f}"
            else:
                headline = f"±${latest_val:.2f}"
                sub = f"±{latest_pct:.2f}%"
            if not single:
                delta = latest_val - first[f"{key}_{conf}"]
                sign = "+" if delta >= 0 else ""
                sub = f"{sub}   ({sign}{delta:.2f} vs first)"
            st.metric(f"Latest {label}", headline, sub)
    with col_d:
        st.metric(
            "ATM IV (annualized)",
            f"{last['iv']*100:.1f}%",
            None if single else f"{d_iv*100:+.2f}pp vs first",
            help=(
                "Annualized at-the-money implied volatility, driving "
                "the moves above. Rising = market pricing in more "
                "uncertainty; falling = vol crush. Spikes into events "
                "(FOMC, CPI, earnings), decays afterward."
            ),
        )
    if single:
        st.caption(
            "Only one snapshot so far — as new snapshots arrive, this "
            "will show how the market's own uncertainty is repricing "
            "throughout the day."
        )


# ---------------------------------------------------------------------------
# Implied vs actual daily moves (history of completed sessions)
# ---------------------------------------------------------------------------

@st.cache_data(ttl=300, show_spinner=False)
def _implied_vs_actual_history(
    ticker: str, num_days: int, end_iso: str,
) -> list[dict]:
    """For each of the ``num_days`` business days ending at ``end_iso``
    (inclusive), pair the implied move that was priced in *before* the
    session with the move that actually happened.

    Key convention (per the section's purpose): the implied numbers for
    day D come from the **latest snapshot captured before D** — normally
    the last batch fire of the prior session — NOT from anything captured
    during D itself. Intraday repricing of D's own implied move lives in
    the "Implied move over time" section above.

    The actual move is measured against that same reference snapshot's
    spot: (last spot captured on D − ref spot) / ref spot. Signed, so a
    down day is negative. Uses the last snapshot of the session as the
    "close", which is exact only if the batch runs near the close.

    One dict per day, oldest → newest:
        {"day", "implied" ({conf: pct} or None), "actual_pct" (or None),
         "ref_spot", "close_spot", "iv", "days_to_exp",
         "implied_captured_at_local", "close_captured_at_local"}
    """
    end = date.fromisoformat(end_iso)
    days = _past_business_days(end, num_days)

    out: list[dict] = []
    for day in days:
        rows = gex_store.recent_snapshots(
            ticker=ticker, expiration_date=day.isoformat(), limit=500
        )
        # rows are newest → oldest, so the first match on each side of
        # the day boundary is the latest one.
        ref = None    # latest snapshot captured BEFORE day (prior session)
        close = None  # latest snapshot captured ON day (session "close")
        for r in rows:
            local_dt = _parse_utc(r["captured_at"]).astimezone()
            ld = local_dt.date()
            if ld == day and close is None:
                close = (r, local_dt)
            elif ld < day and ref is None:
                ref = (r, local_dt)
            if ref is not None and close is not None:
                break

        entry: dict = {
            "day": day,
            "implied": None,
            "actual_pct": None,
            "ref_spot": None,
            "close_spot": None,
            "iv": None,
            "days_to_exp": None,
            "implied_captured_at_local": None,
            "close_captured_at_local": None,
        }
        if ref is not None:
            r, local_dt = ref
            spot = float(r["spot_price"])
            iv = _atm_iv_from_strikes(gex_store.get_strikes(r["id"]), spot)
            days_to_exp = _business_days_between(local_dt.date(), day)
            if iv is not None and days_to_exp > 0:
                entry["implied"] = {
                    conf: iv * math.sqrt(days_to_exp / 252.0) * Z_BY_CONF[conf] * 100.0
                    for conf, _, _ in IMPLIED_MOVE_LEVELS
                }
                entry["ref_spot"] = spot
                entry["iv"] = iv
                entry["days_to_exp"] = days_to_exp
                entry["implied_captured_at_local"] = local_dt
        if close is not None and entry["ref_spot"] is not None:
            rc, close_dt = close
            close_spot = float(rc["spot_price"])
            entry["close_spot"] = close_spot
            entry["close_captured_at_local"] = close_dt
            entry["actual_pct"] = (
                (close_spot - entry["ref_spot"]) / entry["ref_spot"] * 100.0
            )
        out.append(entry)
    return out


def _render_implied_vs_actual_chart(ticker: str, history: list[dict]) -> None:
    if not any(
        h["implied"] is not None or h["actual_pct"] is not None for h in history
    ):
        st.info(
            f"No history yet for {ticker} on these days. Each completed "
            "session needs a snapshot from the prior day (for the implied "
            "move) and one during the session itself (for the actual move)."
        )
        return

    labels = [f"{h['day'].strftime('%b %d')} ({h['day'].strftime('%a')})" for h in history]

    fig = go.Figure()

    # Implied bands: symmetric ±σ lines. The negative twin shares a
    # legend group so one legend click toggles both sides.
    for i, (conf, label, color) in enumerate(IMPLIED_MOVE_LEVELS):
        vals = [h["implied"][conf] if h["implied"] else None for h in history]
        customdata = [
            [
                h["implied"][conf] if h["implied"] else 0.0,
                h["ref_spot"] or 0.0,
                (h["iv"] or 0.0) * 100,
                h["implied_captured_at_local"].strftime("%b %d %H:%M")
                if h["implied_captured_at_local"] else "n/a",
            ]
            for h in history
        ]
        if i == 0:
            hover = (
                "Priced from snapshot <b>%{customdata[3]}</b>  ·  "
                "ref spot <b>$%{customdata[1]:.2f}</b>  ·  "
                "ATM IV <b>%{customdata[2]:.1f}%</b><br>"
                f"±{label} implied: <b>±%{{customdata[0]:.2f}}%</b>"
                "<extra></extra>"
            )
        else:
            hover = (
                f"±{label} implied: <b>±%{{customdata[0]:.2f}}%</b>"
                "<extra></extra>"
            )
        fig.add_trace(go.Scatter(
            x=labels, y=vals,
            mode="lines+markers",
            name=f"±{label} implied",
            legendgroup=f"sigma{i}",
            line=dict(color=color, width=2, dash="dot"),
            marker=dict(size=8, color=color),
            connectgaps=False,
            customdata=customdata,
            hovertemplate=hover,
        ))
        fig.add_trace(go.Scatter(
            x=labels,
            y=[-v if v is not None else None for v in vals],
            mode="lines+markers",
            legendgroup=f"sigma{i}",
            showlegend=False,
            line=dict(color=color, width=2, dash="dot"),
            marker=dict(size=8, color=color),
            connectgaps=False,
            hoverinfo="skip",
        ))

    actual_vals = [h["actual_pct"] for h in history]
    bar_colors = [
        "#2ca02c" if (v is not None and v >= 0) else "#d62728"
        for v in actual_vals
    ]
    bar_customdata = [
        [
            h["ref_spot"] or 0.0,
            h["close_spot"] or 0.0,
            h["close_captured_at_local"].strftime("%b %d %H:%M")
            if h["close_captured_at_local"] else "n/a",
        ]
        for h in history
    ]
    fig.add_trace(go.Bar(
        x=labels, y=actual_vals,
        name="Actual move",
        marker_color=bar_colors,
        opacity=0.75,
        width=0.45,
        customdata=bar_customdata,
        hovertemplate=(
            "Actual: <b>%{y:+.2f}%</b>  "
            "($%{customdata[0]:.2f} → $%{customdata[1]:.2f}, "
            "last snapshot %{customdata[2]})<extra></extra>"
        ),
    ))

    fig.add_hline(y=0, line_color="#999", line_width=1)
    fig.update_layout(
        title=f"{ticker} — implied (from prior session) vs actual daily move",
        xaxis_title="Session",
        yaxis_title="Move (% of prior-session spot)",
        height=420,
        hovermode="x unified",
        legend=dict(orientation="h", y=1.08, x=0),
        margin=dict(t=60, l=60, r=20, b=40),
        barmode="overlay",
    )
    fig.update_xaxes(type="category")
    fig.update_yaxes(ticksuffix="%")

    st.plotly_chart(fig, use_container_width=True)

    scored = [
        h for h in history
        if h["actual_pct"] is not None and h["implied"] is not None
    ]
    col_a, col_b, col_c, col_d = st.columns(4)
    conf1, conf2 = IMPLIED_MOVE_LEVELS[0][0], IMPLIED_MOVE_LEVELS[1][0]
    with col_a:
        if scored:
            n1 = sum(1 for h in scored if abs(h["actual_pct"]) <= h["implied"][conf1])
            st.metric(
                "Days within ±1σ",
                f"{n1}/{len(scored)}",
                help=(
                    "If the options market prices risk correctly, "
                    "~68% of sessions should land inside the 1σ band."
                ),
            )
        else:
            st.metric("Days within ±1σ", "n/a")
    with col_b:
        if scored:
            n2 = sum(1 for h in scored if abs(h["actual_pct"]) <= h["implied"][conf2])
            st.metric(
                "Days within ±2σ",
                f"{n2}/{len(scored)}",
                help="~95% of sessions should land inside the 2σ band.",
            )
        else:
            st.metric("Days within ±2σ", "n/a")
    with col_c:
        if scored:
            last = scored[-1]
            st.metric(
                f"Last scored day ({last['day'].strftime('%b %d')})",
                f"{last['actual_pct']:+.2f}%",
                f"±{last['implied'][conf1]:.2f}% was 1σ implied",
                delta_color="off",
            )
        else:
            st.metric("Last scored day", "n/a")
    with col_d:
        if scored:
            big = max(scored, key=lambda h: abs(h["actual_pct"]))
            st.metric(
                "Biggest move",
                f"{big['actual_pct']:+.2f}%",
                big["day"].strftime("%b %d"),
                delta_color="off",
            )
        else:
            st.metric("Biggest move", "n/a")


def _crossing_history(
    ticker: str, expiration: date, range_pct: float = 5.0,
) -> list[dict]:
    """For each snapshot of (ticker, expiration), compute the cumulative
    dollar-OI crossing strike and pair it with the spot at that moment.

    ``range_pct`` MUST match what the PNG uses (default 5.0 = ±5% of
    spot) or the values won't line up. Passing ``0`` includes the whole
    chain — which lets deep-OTM long-tail OI dominate the crossing and
    produces a wildly different (and much less meaningful) number.

    Returns a list of dicts sorted oldest → newest so plotting is a
    straight time series. Skips snapshots that don't have enough data to
    compute a crossing (e.g. one-sided chains).
    """
    rows = gex_store.recent_snapshots(
        ticker=ticker, expiration_date=expiration.isoformat(), limit=500
    )
    if not rows:
        return []

    history: list[dict] = []
    for r in rows:
        df = _load_oi_snapshot_df(r)
        if df is None or df.empty:
            continue
        spot = float(r["spot_price"])
        series = _prepare_oi_series(
            df, spot=spot, metric="dollars", range_pct=range_pct,
        )
        if series is None:
            continue
        call_cum = np.cumsum(series["call_vals"])
        put_arr = np.array(series["put_vals_positive"])
        put_cum = np.cumsum(put_arr[::-1])[::-1]
        cx, cy = _find_curve_crossing(series["strikes"], call_cum, put_cum)
        if cx is None:
            continue
        history.append({
            "captured_at_utc": _parse_utc(r["captured_at"]),
            "captured_at_local": _parse_utc(r["captured_at"]).astimezone(),
            "crossing_strike": float(cx),
            "crossing_dollars": float(cy) if cy is not None else None,
            "spot_price": spot,
        })

    history.sort(key=lambda h: h["captured_at_utc"])
    return history


# ---------------------------------------------------------------------------
# Positioning totals time series (calls vs puts) — OI (daily) or Volume (intraday)
# ---------------------------------------------------------------------------

# Per-metric config used by the helper + renderer. Adding a new metric
# (e.g. "gex") is a matter of extending this dict + a matching branch
# in _positioning_history().
_METRIC_CONFIG: dict[str, dict] = {
    "oi": {
        "label": "Open Interest",
        "cadence": "daily",  # dedup snapshots by local date
        "call_col": "call_oi",
        "put_col": "put_oi",
        "unit": "contracts",
        "y_title": "Open interest (contracts)",
        "hover_metric": "OI",
        "ratio_label": "Put/Call OI ratio",
        "ratio_help": (
            "Total put OI ÷ total call OI. >1 = more puts than calls "
            "outstanding (defensive positioning). <1 = call-heavy "
            "(bullish or short-vol positioning)."
        ),
        "single_caption": (
            "Only one day of data so far — OI settles daily, so this "
            "chart fills in one point per trading session as snapshots "
            "accumulate."
        ),
    },
    "volume": {
        "label": "Volume",
        "cadence": "intraday",  # every snapshot, no dedup
        "call_col": "call_volume",
        "put_col": "put_volume",
        "unit": "contracts",
        "y_title": "Volume (contracts, cumulative for session)",
        "hover_metric": "Volume",
        "ratio_label": "Put/Call volume ratio",
        "ratio_help": (
            "Total put volume ÷ total call volume. >1 = more puts "
            "traded today than calls (bearish flow). <1 = call-heavy "
            "flow. Session volume is cumulative and resets each morning."
        ),
        "single_caption": (
            "Only one snapshot so far — volume ticks continuously "
            "during market hours, so this chart fills in with each "
            "batch fire."
        ),
    },
}


def _positioning_history(
    ticker: str, expiration: date, metric: str,
) -> list[dict]:
    """Total call/put positioning per snapshot for this expiration.

    * ``metric='oi'`` → dedupe by local date (OI ticks daily; multiple
      snapshots per day would just repeat the same value).
    * ``metric='volume'`` → keep every snapshot (volume ticks continuously
      during the session).

    Returned dicts are pre-normalized so the renderer treats OI and
    volume identically:
        {"x": <date | datetime>, "call_val", "put_val", "pc_ratio",
         "captured_at_utc", "captured_at_local", "spot_price"}
    Sorted oldest → newest.
    """
    cfg = _METRIC_CONFIG[metric]
    call_col = cfg["call_col"]
    put_col = cfg["put_col"]

    rows = gex_store.recent_snapshots(
        ticker=ticker, expiration_date=expiration.isoformat(), limit=500
    )
    if not rows:
        return []

    def _entry(r) -> dict:
        local_dt = _parse_utc(r["captured_at"]).astimezone()
        call_val = int(r[call_col])
        put_val = int(r[put_col])
        return {
            "x": local_dt.date() if cfg["cadence"] == "daily" else local_dt,
            "call_val": call_val,
            "put_val": put_val,
            "pc_ratio": (put_val / call_val) if call_val > 0 else None,
            "captured_at_utc": _parse_utc(r["captured_at"]),
            "captured_at_local": local_dt,
            "spot_price": float(r["spot_price"]),
        }

    if cfg["cadence"] == "daily":
        by_date: dict[date, dict] = {}
        for r in rows:
            e = _entry(r)
            d = e["x"]
            # Keep the *latest* snapshot per local day
            if d not in by_date or e["captured_at_local"] > by_date[d]["captured_at_local"]:
                by_date[d] = e
        return sorted(by_date.values(), key=lambda h: h["x"])

    # intraday
    entries = [_entry(r) for r in rows]
    entries.sort(key=lambda h: h["captured_at_utc"])
    return entries


def _render_positioning_chart(
    ticker: str, expiration: date, history: list[dict], metric: str,
) -> None:
    cfg = _METRIC_CONFIG[metric]
    if not history:
        st.info(
            f"No snapshots yet for {ticker} {expiration.isoformat()}. "
            "Run **oi-dashboard** at least once to seed the history."
        )
        return

    xs = [h["x"] for h in history]
    call_vals = [h["call_val"] for h in history]
    put_vals = [h["put_val"] for h in history]
    single = len(history) == 1

    hover_x_fmt = "%Y-%m-%d" if cfg["cadence"] == "daily" else "%Y-%m-%d %H:%M"

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=xs, y=call_vals,
        mode="markers" if single else "lines+markers",
        name=f"Call {cfg['hover_metric']} (total)",
        line=dict(color="#2ca02c", width=2.5),
        marker=dict(size=12 if single else 8, color="#2ca02c"),
        hovertemplate=(
            f"<b>%{{x|{hover_x_fmt}}}</b><br>"
            f"Call {cfg['hover_metric']}: <b>%{{y:,.0f}}</b> "
            f"{cfg['unit']}<extra></extra>"
        ),
    ))
    fig.add_trace(go.Scatter(
        x=xs, y=put_vals,
        mode="markers" if single else "lines+markers",
        name=f"Put {cfg['hover_metric']} (total)",
        line=dict(color="#d62728", width=2.5),
        marker=dict(size=12 if single else 8, color="#d62728"),
        hovertemplate=(
            f"<b>%{{x|{hover_x_fmt}}}</b><br>"
            f"Put {cfg['hover_metric']}: <b>%{{y:,.0f}}</b> "
            f"{cfg['unit']}<extra></extra>"
        ),
    ))

    unit_desc = "day" if cfg["cadence"] == "daily" else "snapshot"
    fig.update_layout(
        title=(
            f"{ticker} {expiration.isoformat()} — total {cfg['label'].lower()}  "
            f"·  {len(history)} {unit_desc}{'s' if len(history) != 1 else ''}"
        ),
        xaxis_title=("Trading day" if cfg["cadence"] == "daily" else "Snapshot time (local)"),
        yaxis_title=cfg["y_title"],
        height=380,
        hovermode="x unified",
        legend=dict(orientation="h", y=1.08, x=0),
        margin=dict(t=60, l=60, r=20, b=40),
    )
    fig.update_yaxes(tickformat=",.0f")
    if single:
        x0 = xs[0]
        if cfg["cadence"] == "daily":
            fig.update_xaxes(range=[x0 - timedelta(days=1), x0 + timedelta(days=1)])
        else:
            fig.update_xaxes(range=[x0 - timedelta(hours=6), x0 + timedelta(hours=6)])
        lo = min(call_vals[0], put_vals[0])
        hi = max(call_vals[0], put_vals[0])
        pad = max((hi - lo) * 1.5, hi * 0.2, 1000)
        fig.update_yaxes(range=[max(0, lo - pad), hi + pad])

    st.plotly_chart(fig, use_container_width=True)

    first, last = history[0], history[-1]
    d_call = last["call_val"] - first["call_val"]
    d_put = last["put_val"] - first["put_val"]
    vs_label = "vs first day" if cfg["cadence"] == "daily" else "vs first snapshot"

    col_a, col_b, col_c, col_d = st.columns(4)
    with col_a:
        st.metric(
            f"Latest call {cfg['hover_metric']}",
            f"{last['call_val']:,}",
            None if single else f"{d_call:+,} {vs_label}",
        )
    with col_b:
        st.metric(
            f"Latest put {cfg['hover_metric']}",
            f"{last['put_val']:,}",
            None if single else f"{d_put:+,} {vs_label}",
        )
    with col_c:
        pc = last["pc_ratio"]
        first_pc = first["pc_ratio"]
        pc_str = f"{pc:.2f}" if pc is not None else "n/a"
        if not single and pc is not None and first_pc is not None:
            pc_delta = f"{pc - first_pc:+.2f} {vs_label}"
        else:
            pc_delta = None
        st.metric(cfg["ratio_label"], pc_str, pc_delta, help=cfg["ratio_help"])
    with col_d:
        if cfg["cadence"] == "daily":
            headline = last["x"].strftime("%b %d")
            sub = _age_from_dt(last["captured_at_utc"])
            help_txt = (
                "Trading day of the freshest snapshot for this "
                "expiration. Delta shows how long ago the snapshot was "
                "captured."
            )
        else:
            headline = _age_from_dt(last["captured_at_utc"])
            sub = last["captured_at_local"].strftime("%H:%M:%S")
            help_txt = (
                "How long ago the batch persisted the freshest "
                "snapshot. Sub-line shows the exact local capture time."
            )
        st.metric("Latest snapshot", headline, sub, help=help_txt)
    if single:
        st.caption(cfg["single_caption"])


def _render_crossing_chart(ticker: str, expiration: date, history: list[dict]) -> None:
    if not history:
        st.info(
            f"No snapshots yet for {ticker} {expiration.isoformat()}. "
            "Run **oi-dashboard** at least once to seed the history."
        )
        return

    ts = [h["captured_at_local"] for h in history]
    cross = [h["crossing_strike"] for h in history]
    spot = [h["spot_price"] for h in history]
    single = len(history) == 1

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=ts, y=cross,
        mode="markers" if single else "lines+markers",
        name="Crossing strike",
        line=dict(color="#1f77b4", width=2.5),
        marker=dict(size=12 if single else 8, color="#1f77b4"),
        hovertemplate=(
            "<b>%{x|%Y-%m-%d %H:%M}</b><br>"
            "Crossing: <b>$%{y:.2f}</b><extra></extra>"
        ),
    ))
    fig.add_trace(go.Scatter(
        x=ts, y=spot,
        mode="markers" if single else "lines+markers",
        name="Spot",
        line=dict(color="#111", dash="dash", width=1.5),
        marker=dict(size=10 if single else 6, symbol="circle-open", color="#111"),
        hovertemplate=(
            "<b>%{x|%Y-%m-%d %H:%M}</b><br>"
            "Spot: <b>$%{y:.2f}</b><extra></extra>"
        ),
    ))

    first, last = history[0], history[-1]
    delta_cross = last["crossing_strike"] - first["crossing_strike"]
    delta_spot = last["spot_price"] - first["spot_price"]
    span_min = (last["captured_at_utc"] - first["captured_at_utc"]).total_seconds() / 60
    if single:
        span_str = "single snapshot"
    else:
        span_str = (
            f"{span_min / 60 / 24:.1f} days" if span_min >= 60 * 24
            else f"{span_min / 60:.1f} hours" if span_min >= 60
            else f"{span_min:.0f} min"
        )

    # With a single point, Plotly's autorange picks a tiny window and the
    # dot floats in the middle of nowhere. Pad the y-axis so the dot + spot
    # sit at a sensible scale, and widen the x-axis so it doesn't look like
    # the chart is broken.
    layout_kwargs: dict = dict(
        title=(
            f"{ticker} {expiration.isoformat()} — crossing strike over time  "
            f"·  {len(history)} snapshot{'s' if len(history) != 1 else ''} "
            f"over {span_str}"
        ),
        xaxis_title="Snapshot time (local)",
        yaxis_title="Strike ($)",
        height=380,
        hovermode="x unified",
        legend=dict(orientation="h", y=1.08, x=0),
        margin=dict(t=60, l=60, r=20, b=40),
    )
    if single:
        t0 = ts[0]
        layout_kwargs["xaxis"] = dict(
            range=[t0 - timedelta(hours=6), t0 + timedelta(hours=6)],
        )
        lo = min(cross[0], spot[0])
        hi = max(cross[0], spot[0])
        pad = max((hi - lo) * 2.0, 2.0)
        layout_kwargs["yaxis"] = dict(range=[lo - pad, hi + pad])

    fig.update_layout(**layout_kwargs)
    fig.update_yaxes(tickformat="$.2f")

    st.plotly_chart(fig, use_container_width=True)

    col_a, col_b, col_c, col_d = st.columns(4)
    with col_a:
        st.metric(
            "Latest crossing",
            f"${last['crossing_strike']:.2f}",
            None if single else f"{delta_cross:+.2f} vs first",
        )
    with col_b:
        st.metric(
            "Latest spot",
            f"${last['spot_price']:.2f}",
            None if single else f"{delta_spot:+.2f} vs first",
        )
    with col_c:
        gap = last["crossing_strike"] - last["spot_price"]
        st.metric(
            "Crossing − spot (now)",
            f"{gap:+.2f}",
            help=(
                "Positive = the pin/max-pain magnet is above spot; "
                "negative = below."
            ),
        )
    with col_d:
        st.metric(
            "Snapshot age",
            _age_from_dt(last["captured_at_utc"]),
            last["captured_at_local"].strftime("%H:%M:%S"),
            help=(
                "How long ago the batch persisted this snapshot to the "
                "DB. If it's climbing past your batch cadence (30 min "
                "by default) the scheduler is stuck — check "
                "`journalctl -u oi-scheduler` or the batch log."
            ),
        )
    if single:
        st.caption(
            "Only one snapshot so far — run `oi-dashboard` again "
            "(or the batch) to start seeing movement over time."
        )


# ---------------------------------------------------------------------------
# Background batch runner
# ---------------------------------------------------------------------------

def _kickoff_batch(
    tickers: list[str],
    start: date,
    end: date,
    refresh_cache: bool,
) -> None:
    """Spawn oi_batch.py as a background subprocess (non-blocking)."""
    cmd = [
        str(BATCH_SCRIPT),
        "--from", start.isoformat(),
        "--to", end.isoformat(),
        "--tickers", ",".join(tickers),
    ]
    if not refresh_cache:
        cmd.append("--no-refresh-cache")

    env = os.environ.copy()
    env.setdefault("UV_NATIVE_TLS", "true")

    log_path = REPO_ROOT / "logs" / "oi-batch" / "_streamlit_last_run.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_file = open(log_path, "w")

    proc = subprocess.Popen(
        cmd, cwd=REPO_ROOT, env=env, stdout=log_file, stderr=subprocess.STDOUT,
    )
    st.session_state["_batch_proc"] = proc
    st.session_state["_batch_log_path"] = str(log_path)
    st.session_state["_batch_started_at"] = time.time()


def _poll_batch() -> str:
    """Return one of: 'idle', 'running', 'done', 'failed'."""
    proc = st.session_state.get("_batch_proc")
    if proc is None:
        return "idle"
    rc = proc.poll()
    if rc is None:
        return "running"
    st.session_state["_batch_rc"] = rc
    st.session_state["_batch_finished_at"] = time.time()
    st.session_state["_batch_proc"] = None
    return "done" if rc == 0 else "failed"


# ---------------------------------------------------------------------------
# Main app
# ---------------------------------------------------------------------------

st.set_page_config(page_title="Options OI Dashboard", layout="wide")
st.title("📊 Options OI — Live Dashboard")

with st.sidebar:
    st.header("Config")
    tickers_str = st.text_input(
        "Tickers (comma-separated)",
        value=st.session_state.get("tickers_str", "SPY"),
        key="tickers_str",
    )
    tickers = [
        t.strip().upper() for t in tickers_str.split(",") if t.strip()
    ]
    days_ahead = st.slider(
        "Business days ahead (starting today)",
        min_value=1, max_value=10, value=5, key="days_ahead",
    )
    refresh_cache = st.toggle(
        "Force fresh Robinhood fetch (slow, ~60–90s per date)",
        value=False, key="refresh_cache",
        help=(
            "Off = use cached options chain (fast; premium may be a few "
            "minutes stale). On = pass --refresh-cache to oi_batch so "
            "every job pulls a live chain."
        ),
    )
    range_pct = st.slider(
        "Crossing range (± % of spot)",
        min_value=1.0, max_value=25.0, value=5.0, step=0.5,
        key="range_pct",
        help=(
            "Filter strikes to ±N% of spot when computing the cumulative-"
            "dollar crossing. **Must match your PNG's --range** for the "
            "dashboard number to line up with the PNG. Default 5% mirrors "
            "`lia oi-dashboard`. Set to 25% for a chain-wide view; "
            "extreme-OTM tail OI will dominate and the crossing loses "
            "meaning below ~3%."
        ),
    )

    st.divider()
    st.subheader("Refresh")
    auto = st.toggle("Auto-refresh every 30s", value=True, key="auto")
    if auto:
        st_autorefresh(interval=30_000, key="_autoref")

    col_r1, col_r2 = st.columns(2)
    with col_r1:
        if st.button("🔄 Refresh view", use_container_width=True):
            st.rerun()
    with col_r2:
        batch_state = _poll_batch()
        run_disabled = batch_state == "running"
        if st.button(
            "▶ Run batch",
            type="primary",
            use_container_width=True,
            disabled=run_disabled,
        ):
            start, end, _ = _compute_range(days_ahead)
            _kickoff_batch(tickers, start, end, refresh_cache)
            st.rerun()


start, end, exps = _compute_range(days_ahead)

top1, top2, top3 = st.columns([2, 2, 3])
with top1:
    st.metric("Range start", start.isoformat())
with top2:
    st.metric("Range end", end.isoformat())
with top3:
    st.metric("Expirations", f"{len(exps)}  ·  {', '.join(t for t in tickers)}")

batch_state = _poll_batch()
if batch_state == "running":
    elapsed = int(time.time() - st.session_state.get("_batch_started_at", time.time()))
    st.warning(
        f"🚀 Batch running… ({elapsed}s elapsed). "
        f"PNGs will appear here as each date finishes; auto-refresh keeps "
        f"the view current."
    )
    log_path = st.session_state.get("_batch_log_path")
    if log_path and Path(log_path).exists():
        with st.expander("Live batch log"):
            st.code(Path(log_path).read_text()[-4000:], language="text")
elif batch_state == "done":
    finished = st.session_state.get("_batch_finished_at")
    if finished:
        st.success(f"✅ Batch completed at {datetime.fromtimestamp(finished).strftime('%H:%M:%S')}")
elif batch_state == "failed":
    rc = st.session_state.get("_batch_rc")
    st.error(f"❌ Batch failed (rc={rc}). See log:")
    log_path = st.session_state.get("_batch_log_path")
    if log_path and Path(log_path).exists():
        st.code(Path(log_path).read_text()[-4000:], language="text")

st.caption(
    f"Dashboard view refreshed at "
    f"**{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}** "
    f"(local). Charts + PNGs are re-read from the DB / disk on every refresh."
)

# ---------------------------------------------------------------------------
# Implied-move time series (68% / 95% / 99.7%) per expiration
# ---------------------------------------------------------------------------
st.divider()
st.header("🎯 Implied move over time")

move_unit = st.radio(
    "Y-axis unit",
    options=["pct", "dollars"],
    format_func=lambda u: "% of spot" if u == "pct" else "Dollars",
    horizontal=True,
    key="move_unit",
    help=(
        "% is comparable across expirations and spot levels. $ is "
        "concrete when comparing to spot moves you see intraday."
    ),
)
st.caption(
    "The `emove` bands (68% / 95% / 99.7%) plotted as time series. "
    "Formula: **spot × ATM IV × √(days/252) × z**. All three inputs "
    "move intraday — ATM IV especially — so the bands widen and "
    "narrow as the market reprices its own uncertainty. Widening "
    "into an event = fear being priced in; narrowing after = vol crush."
)

for ticker in tickers:
    if not exps:
        continue
    tabs = st.tabs([f"{exp.isoformat()} ({exp.strftime('%a')})" for exp in exps])
    for tab, exp in zip(tabs, exps):
        with tab:
            st.markdown(f"**{ticker} · {exp.isoformat()}**")
            move_hist = _implied_move_history(ticker, exp.isoformat())
            _render_implied_move_chart(ticker, exp, move_hist, unit=move_unit)

# ---------------------------------------------------------------------------
# Implied vs actual daily moves (completed sessions)
# ---------------------------------------------------------------------------
st.divider()
st.header("📏 Implied vs actual daily moves")

iva_days = st.selectbox(
    "History window",
    options=[5, 10, 15, 20],
    index=0,
    format_func=lambda n: f"Last {n} working days",
    key="iva_days",
)
_iva_end = _prev_business_day(date.today())
st.caption(
    f"Completed sessions only — the last {iva_days} trading days ending "
    f"**{_iva_end.strftime('%b %d')}** (weekends skipped). Dotted lines are "
    "the ±1σ / ±2σ / ±3σ implied moves **as priced before each session "
    "opened** (latest snapshot from the prior day — intraday repricing of "
    "the day itself is deliberately excluded; that lives in the section "
    "above). Bars are the actual move vs that same prior-day spot: green "
    "up, red down. A bar poking outside a dotted band = the market moved "
    "more than options had priced in."
)

for ticker in tickers:
    st.markdown(f"**{ticker}**")
    iva_hist = _implied_vs_actual_history(ticker, iva_days, _iva_end.isoformat())
    _render_implied_vs_actual_chart(ticker, iva_hist)

# ---------------------------------------------------------------------------
# Crossing-strike time series (interactive, one per ticker × expiration)
# ---------------------------------------------------------------------------
st.divider()
st.header("📈 Crossing strike over time")
st.caption(
    "Where the cumulative-dollar call and put curves cross — the "
    "positioning-weighted 'pin' strike. Each `oi-dashboard` run adds a "
    "point. Watch for drift: crossing moving toward or away from spot."
)

for ticker in tickers:
    if not exps:
        continue
    tabs = st.tabs([f"{exp.isoformat()} ({exp.strftime('%a')})" for exp in exps])
    for tab, exp in zip(tabs, exps):
        with tab:
            st.markdown(
                f"**{ticker} · {exp.isoformat()}**  "
                f"_(crossing computed on ±{range_pct:.1f}% of spot)_"
            )
            history = _crossing_history(ticker, exp, range_pct=range_pct)
            _render_crossing_chart(ticker, exp, history)

# ---------------------------------------------------------------------------
# Positioning totals (calls vs puts) — toggle OI (daily) or Volume (intraday)
# ---------------------------------------------------------------------------
st.divider()
st.header("📅 Positioning totals — calls vs puts")

positioning_metric = st.radio(
    "Metric",
    options=["oi", "volume"],
    format_func=lambda m: (
        "Open Interest (daily — settles once per session)"
        if m == "oi" else
        "Volume (intraday — ticks continuously)"
    ),
    horizontal=True,
    key="positioning_metric",
    help=(
        "OI = total contracts outstanding, settled EOD by OCC. Best "
        "signal for **positioning shifts across days**. Volume = "
        "contracts traded during the session, resets each morning. "
        "Best for **intraday flow direction**."
    ),
)
_metric_cfg = _METRIC_CONFIG[positioning_metric]
st.caption(
    f"Total {_metric_cfg['label'].lower()} across ALL strikes for each "
    f"expiration, one point per "
    f"{'trading day' if _metric_cfg['cadence'] == 'daily' else 'snapshot'}. "
    + (
        "Rising put line = defensive positioning being layered in; "
        "rising call line = long/bullish or covered-call flow. "
        "OI is settled once per day by the OCC."
        if positioning_metric == "oi" else
        "Volume shows what's changing hands *right now* — cumulative "
        "from the morning bell. Rising put volume vs calls signals "
        "hedging flow starting; rising call volume signals bullish "
        "flow or short-vol writers."
    )
)

for ticker in tickers:
    if not exps:
        continue
    tabs = st.tabs([f"{exp.isoformat()} ({exp.strftime('%a')})" for exp in exps])
    for tab, exp in zip(tabs, exps):
        with tab:
            st.markdown(f"**{ticker} · {exp.isoformat()}**")
            hist = _positioning_history(ticker, exp, metric=positioning_metric)
            _render_positioning_chart(
                ticker, exp, hist, metric=positioning_metric,
            )

# ---------------------------------------------------------------------------
# PNG grid (the three-panel dashboard as static images for now)
# ---------------------------------------------------------------------------
st.divider()
st.header("🖼 Latest dashboard PNGs")
st.caption(
    "The full 3-panel `oi-dashboard` snapshots as generated by `oi_batch.py`. "
    "Interactive Plotly versions of these panels are a natural next step."
)

for ticker in tickers:
    st.subheader(f"{ticker}")
    if not exps:
        st.info("No business days in the selected range.")
        continue
    cols = st.columns(len(exps))
    for col, exp in zip(cols, exps):
        with col:
            path = _png_for(ticker, exp)
            age = _age_str(path)
            weekday = exp.strftime("%a")
            st.markdown(f"**{exp.isoformat()}** ({weekday})  ·  _{age}_")
            if path.exists():
                st.image(str(path), use_container_width=True)
            else:
                st.info(
                    "No PNG yet.\n\n"
                    "Click **▶ Run batch** in the sidebar to generate it."
                )
