"""Streamlit dashboard for `lia oi-dashboard` — live rolling view of the
current week's expirations.

Renders one column per expiration date across the next N business days
(default 5, starting today or the next business day if it's a weekend).
Auto-refreshes every 30s so any PNG regenerated by `oi_batch.py` — either
manually via the "Run batch now" button, or by a background cron — shows
up here without a page reload.

Run locally:

    UV_NATIVE_TLS=true uv run streamlit run scripts/oi_dashboard_app.py

Open in your browser at the URL Streamlit prints (usually
http://localhost:8501).
"""
from __future__ import annotations

import os
import subprocess
import time
from datetime import date, datetime, timedelta
from pathlib import Path

import streamlit as st
from streamlit_autorefresh import st_autorefresh

REPO_ROOT = Path(__file__).resolve().parent.parent
PLOTS_DIR = REPO_ROOT / "plots"
BATCH_SCRIPT = REPO_ROOT / "scripts" / "oi_batch.py"


# ---------------------------------------------------------------------------
# Date helpers
# ---------------------------------------------------------------------------

def _next_business_day(d: date) -> date:
    while d.weekday() >= 5:
        d += timedelta(days=1)
    return d


def _add_business_days(d: date, n: int) -> date:
    """Return the date `n` business days after `d` (n=0 → d itself)."""
    while n > 0:
        d += timedelta(days=1)
        if d.weekday() < 5:
            n -= 1
    return d


def _compute_range(days_ahead: int) -> tuple[date, date, list[date]]:
    start = _next_business_day(date.today())
    end = _add_business_days(start, days_ahead - 1)
    exps: list[date] = []
    d = start
    while d <= end:
        if d.weekday() < 5:
            exps.append(d)
        d += timedelta(days=1)
    return start, end, exps


# ---------------------------------------------------------------------------
# PNG helpers
# ---------------------------------------------------------------------------

def _png_for(ticker: str, exp: date) -> Path:
    return PLOTS_DIR / f"oi-dashboard-{ticker}-{exp.isoformat()}.png"


def _age_str(path: Path) -> str:
    if not path.exists():
        return "not generated"
    mtime = datetime.fromtimestamp(path.stat().st_mtime)
    delta = datetime.now() - mtime
    secs = int(delta.total_seconds())
    if secs < 60:
        return f"{secs}s ago"
    if secs < 3600:
        return f"{secs // 60}m ago"
    if secs < 86400:
        return f"{secs // 3600}h {(secs % 3600) // 60}m ago"
    return f"{secs // 86400}d ago"


# ---------------------------------------------------------------------------
# Background batch runner
# ---------------------------------------------------------------------------

def _kickoff_batch(
    tickers: list[str],
    start: date,
    end: date,
    refresh_cache: bool,
) -> None:
    """Spawn oi_batch.py as a background subprocess (non-blocking)."""
    cmd = [
        str(BATCH_SCRIPT),
        "--from", start.isoformat(),
        "--to", end.isoformat(),
        "--tickers", ",".join(tickers),
    ]
    if not refresh_cache:
        cmd.append("--no-refresh-cache")

    env = os.environ.copy()
    env.setdefault("UV_NATIVE_TLS", "true")

    log_path = REPO_ROOT / "logs" / "oi-batch" / "_streamlit_last_run.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_file = open(log_path, "w")

    proc = subprocess.Popen(
        cmd, cwd=REPO_ROOT, env=env, stdout=log_file, stderr=subprocess.STDOUT,
    )
    st.session_state["_batch_proc"] = proc
    st.session_state["_batch_log_path"] = str(log_path)
    st.session_state["_batch_started_at"] = time.time()


def _poll_batch() -> str:
    """Return one of: 'idle', 'running', 'done', 'failed'."""
    proc = st.session_state.get("_batch_proc")
    if proc is None:
        return "idle"
    rc = proc.poll()
    if rc is None:
        return "running"
    st.session_state["_batch_rc"] = rc
    st.session_state["_batch_finished_at"] = time.time()
    st.session_state["_batch_proc"] = None
    return "done" if rc == 0 else "failed"


# ---------------------------------------------------------------------------
# Main app
# ---------------------------------------------------------------------------

st.set_page_config(page_title="Options OI Dashboard", layout="wide")
st.title("📊 Options OI — Live Dashboard")

with st.sidebar:
    st.header("Config")
    tickers_str = st.text_input(
        "Tickers (comma-separated)",
        value=st.session_state.get("tickers_str", "SPY"),
        key="tickers_str",
    )
    tickers = [
        t.strip().upper() for t in tickers_str.split(",") if t.strip()
    ]
    days_ahead = st.slider(
        "Business days ahead (starting today)",
        min_value=1, max_value=10, value=5, key="days_ahead",
    )
    refresh_cache = st.toggle(
        "Force fresh Robinhood fetch (slow, ~60–90s per date)",
        value=False, key="refresh_cache",
        help=(
            "Off = use cached options chain (fast; premium may be a few "
            "minutes stale). On = pass --refresh-cache to oi_batch so "
            "every job pulls a live chain."
        ),
    )

    st.divider()
    st.subheader("Refresh")
    auto = st.toggle("Auto-refresh every 30s", value=True, key="auto")
    if auto:
        st_autorefresh(interval=30_000, key="_autoref")

    col_r1, col_r2 = st.columns(2)
    with col_r1:
        if st.button("🔄 Refresh view", use_container_width=True):
            st.rerun()
    with col_r2:
        batch_state = _poll_batch()
        run_disabled = batch_state == "running"
        if st.button(
            "▶ Run batch",
            type="primary",
            use_container_width=True,
            disabled=run_disabled,
        ):
            start, end, _ = _compute_range(days_ahead)
            _kickoff_batch(tickers, start, end, refresh_cache)
            st.rerun()


start, end, exps = _compute_range(days_ahead)

top1, top2, top3 = st.columns([2, 2, 3])
with top1:
    st.metric("Range start", start.isoformat())
with top2:
    st.metric("Range end", end.isoformat())
with top3:
    st.metric("Expirations", f"{len(exps)}  ·  {', '.join(t for t in tickers)}")

batch_state = _poll_batch()
if batch_state == "running":
    elapsed = int(time.time() - st.session_state.get("_batch_started_at", time.time()))
    st.warning(
        f"🚀 Batch running… ({elapsed}s elapsed). "
        f"PNGs will appear here as each date finishes; auto-refresh keeps "
        f"the view current."
    )
    log_path = st.session_state.get("_batch_log_path")
    if log_path and Path(log_path).exists():
        with st.expander("Live batch log"):
            st.code(Path(log_path).read_text()[-4000:], language="text")
elif batch_state == "done":
    finished = st.session_state.get("_batch_finished_at")
    if finished:
        st.success(f"✅ Batch completed at {datetime.fromtimestamp(finished).strftime('%H:%M:%S')}")
elif batch_state == "failed":
    rc = st.session_state.get("_batch_rc")
    st.error(f"❌ Batch failed (rc={rc}). See log:")
    log_path = st.session_state.get("_batch_log_path")
    if log_path and Path(log_path).exists():
        st.code(Path(log_path).read_text()[-4000:], language="text")

st.caption(
    f"Dashboard view refreshed at "
    f"**{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}** "
    f"(local). PNGs are re-read from disk on every refresh."
)

# ---------------------------------------------------------------------------
# PNG grid
# ---------------------------------------------------------------------------
for ticker in tickers:
    st.subheader(f"{ticker}")
    if not exps:
        st.info("No business days in the selected range.")
        continue
    cols = st.columns(len(exps))
    for col, exp in zip(cols, exps):
        with col:
            path = _png_for(ticker, exp)
            age = _age_str(path)
            weekday = exp.strftime("%a")
            st.markdown(f"**{exp.isoformat()}** ({weekday})  ·  _{age}_")
            if path.exists():
                st.image(str(path), use_container_width=True)
            else:
                st.info(
                    "No PNG yet.\n\n"
                    "Click **▶ Run batch** in the sidebar to generate it."
                )
